name = "Simplex"
uuid = "1b950094-d548-4fb7-8e29-cb0908c95717"
authors = ["LEAXPS-15\\lkape <lkapelevich@yahoo.com.au>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
